spring:
  flyway:
    locations: classpath:migration

  datasource:
    url: postgresql://postgres:gUViOqPplYHyHdJgLpMZdsfTPPhehqPA@postgres.railway.internal:5432/railway
    username: postgres
    password: gUViOqPplYHyHdJgLpMZdsfTPPhehqPA
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html